//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Inputs/MADAControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Inputs/MADAControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @MADAControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @MADAControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MADAControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""527ee625-e115-46aa-87d1-e24dc4c2b01d"",
            ""actions"": [
                {
                    ""name"": ""ConfirmDot"",
                    ""type"": ""Button"",
                    ""id"": ""30ef92e1-a098-4d34-9c36-6f22f8f66bdc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeleteDot"",
                    ""type"": ""Button"",
                    ""id"": ""90a9fcc3-3146-4b5b-b679-31503871a198"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeleteMarcher"",
                    ""type"": ""Button"",
                    ""id"": ""7faf4941-d180-49df-9635-ec65582b2b65"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectAll"",
                    ""type"": ""Button"",
                    ""id"": ""d081f42d-5477-411d-be44-d27eaa30af40"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GizmoPosition"",
                    ""type"": ""Button"",
                    ""id"": ""fc779c59-2321-49ca-9043-67fad230ed80"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GizmoRotate"",
                    ""type"": ""Button"",
                    ""id"": ""ce7707f4-a3d4-4cb6-8a8b-6b43e415ea06"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GizmoScale"",
                    ""type"": ""Button"",
                    ""id"": ""da92e1b3-3b7a-485a-b697-d1030626a6d2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SnapToGrid"",
                    ""type"": ""Button"",
                    ""id"": ""897a3434-ab85-4c0b-927d-67be34a900e2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RespaceToBox"",
                    ""type"": ""Button"",
                    ""id"": ""7a16e955-4eff-4e2a-bb55-91c9c2a6dbfa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FocusCamera"",
                    ""type"": ""Button"",
                    ""id"": ""7f87a380-1a00-47a2-bd9b-e75ecb0ee0c4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraZoomScroll"",
                    ""type"": ""Value"",
                    ""id"": ""7adad231-fdb6-4e99-ae36-ee3e789c3c03"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraRotate"",
                    ""type"": ""Value"",
                    ""id"": ""35750d3f-f1bb-45b3-bdb4-a0c15802a73b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraPivot"",
                    ""type"": ""Value"",
                    ""id"": ""8689f866-ae6d-4541-b8e0-45413885efae"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraPan"",
                    ""type"": ""Value"",
                    ""id"": ""9df3f628-3b05-4f71-a57d-7d344b529c9b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchContact0"",
                    ""type"": ""PassThrough"",
                    ""id"": ""31341ec0-87af-4e91-a46c-91a06fa7ea9b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchContact1"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0be2b207-48e7-4310-8b8a-326dbc6fa3bb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchDelta0"",
                    ""type"": ""PassThrough"",
                    ""id"": ""37cc263f-2dd2-4e6b-ba0e-d6ddbe477a31"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchDelta1"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d1460c3d-b85b-42ed-bc83-16edd5ab52c8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchCount"",
                    ""type"": ""Value"",
                    ""id"": ""51e51e04-6ffd-42a5-bdb5-1fdc0c2ef87d"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e19c2ff4-551b-4b4c-bec8-b65752eabc4a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmDot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88876458-c849-4a0d-a4cf-a1469804aaba"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeleteDot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""f4d1a596-8de0-4ed0-ab83-45badb64a482"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeleteMarcher"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7b004666-8d3e-4039-8d9d-e13396d5c926"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeleteMarcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""59a90f5c-d1bd-4f2a-9294-aa8f68e9cd50"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeleteMarcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c78bfde1-d8d2-4b12-91eb-28af5c157ec3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0590ac9a-9ff4-47f1-a2bc-dda844b25094"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SnapToGrid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3322657e-6247-4130-afe3-b569c93cf9f2"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RespaceToBox"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed0def02-7693-4351-8f82-8693109147ba"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FocusCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3951df22-61f0-42ba-8176-f545ebe67013"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoomScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ef330b7-0ab1-4e9c-be2f-c2f42f098837"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoomScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""8369dbcd-b2bd-4c43-98aa-c5707ff393bc"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7c283a5f-c594-4cd4-9c59-9e6d21d78f4d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d1f5ebed-57d8-405e-b797-3ae9e612636a"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""78308358-8d24-420f-8d0d-3fcfd4c29e5d"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPivot"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""3047d513-dc9b-4624-851c-112babc82fd4"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPivot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""10ead4ab-03d0-4ee1-967a-7bc9b1c17fce"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPivot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""1b687439-b127-40d5-bf4c-da186ccb9135"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPivot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""679f699c-0f1e-449d-b14a-3b11da033a88"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPan"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""37b3047f-4cc1-4400-88ac-499bf90f2b26"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""be18b327-30ed-42e3-9167-a59d9fbe1f4d"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9afbab4c-54e4-40d6-a42b-2cef63ff5586"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchContact0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2116fe9-ec1a-4296-9271-5708fd300b56"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchContact1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b38ac48f-4c57-4844-88c4-eef3b07d16ea"",
                    ""path"": ""<Touchscreen>/touch0/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDelta0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31d21340-eeb8-4ac0-bc60-4f799025d387"",
                    ""path"": ""<Touchscreen>/touch1/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDelta1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a6ca5a9-17a8-431e-83e1-70fa9e747ef2"",
                    ""path"": ""<Touchscreen>/touchCount "",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchCount"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13d26783-a869-4c7f-ab32-6113e98f6209"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GizmoPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d877f1c2-1847-455f-adab-0b4c53e60254"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GizmoRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6ee4c71-3400-44d5-b4c4-1731d0dc31cd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GizmoScale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_ConfirmDot = m_Gameplay.FindAction("ConfirmDot", throwIfNotFound: true);
        m_Gameplay_DeleteDot = m_Gameplay.FindAction("DeleteDot", throwIfNotFound: true);
        m_Gameplay_DeleteMarcher = m_Gameplay.FindAction("DeleteMarcher", throwIfNotFound: true);
        m_Gameplay_SelectAll = m_Gameplay.FindAction("SelectAll", throwIfNotFound: true);
        m_Gameplay_GizmoPosition = m_Gameplay.FindAction("GizmoPosition", throwIfNotFound: true);
        m_Gameplay_GizmoRotate = m_Gameplay.FindAction("GizmoRotate", throwIfNotFound: true);
        m_Gameplay_GizmoScale = m_Gameplay.FindAction("GizmoScale", throwIfNotFound: true);
        m_Gameplay_SnapToGrid = m_Gameplay.FindAction("SnapToGrid", throwIfNotFound: true);
        m_Gameplay_RespaceToBox = m_Gameplay.FindAction("RespaceToBox", throwIfNotFound: true);
        m_Gameplay_FocusCamera = m_Gameplay.FindAction("FocusCamera", throwIfNotFound: true);
        m_Gameplay_CameraZoomScroll = m_Gameplay.FindAction("CameraZoomScroll", throwIfNotFound: true);
        m_Gameplay_CameraRotate = m_Gameplay.FindAction("CameraRotate", throwIfNotFound: true);
        m_Gameplay_CameraPivot = m_Gameplay.FindAction("CameraPivot", throwIfNotFound: true);
        m_Gameplay_CameraPan = m_Gameplay.FindAction("CameraPan", throwIfNotFound: true);
        m_Gameplay_TouchContact0 = m_Gameplay.FindAction("TouchContact0", throwIfNotFound: true);
        m_Gameplay_TouchContact1 = m_Gameplay.FindAction("TouchContact1", throwIfNotFound: true);
        m_Gameplay_TouchDelta0 = m_Gameplay.FindAction("TouchDelta0", throwIfNotFound: true);
        m_Gameplay_TouchDelta1 = m_Gameplay.FindAction("TouchDelta1", throwIfNotFound: true);
        m_Gameplay_TouchCount = m_Gameplay.FindAction("TouchCount", throwIfNotFound: true);
    }

    ~@MADAControls()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, MADAControls.Gameplay.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_ConfirmDot;
    private readonly InputAction m_Gameplay_DeleteDot;
    private readonly InputAction m_Gameplay_DeleteMarcher;
    private readonly InputAction m_Gameplay_SelectAll;
    private readonly InputAction m_Gameplay_GizmoPosition;
    private readonly InputAction m_Gameplay_GizmoRotate;
    private readonly InputAction m_Gameplay_GizmoScale;
    private readonly InputAction m_Gameplay_SnapToGrid;
    private readonly InputAction m_Gameplay_RespaceToBox;
    private readonly InputAction m_Gameplay_FocusCamera;
    private readonly InputAction m_Gameplay_CameraZoomScroll;
    private readonly InputAction m_Gameplay_CameraRotate;
    private readonly InputAction m_Gameplay_CameraPivot;
    private readonly InputAction m_Gameplay_CameraPan;
    private readonly InputAction m_Gameplay_TouchContact0;
    private readonly InputAction m_Gameplay_TouchContact1;
    private readonly InputAction m_Gameplay_TouchDelta0;
    private readonly InputAction m_Gameplay_TouchDelta1;
    private readonly InputAction m_Gameplay_TouchCount;
    /// <summary>
    /// Provides access to input actions defined in input action map "Gameplay".
    /// </summary>
    public struct GameplayActions
    {
        private @MADAControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GameplayActions(@MADAControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/ConfirmDot".
        /// </summary>
        public InputAction @ConfirmDot => m_Wrapper.m_Gameplay_ConfirmDot;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/DeleteDot".
        /// </summary>
        public InputAction @DeleteDot => m_Wrapper.m_Gameplay_DeleteDot;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/DeleteMarcher".
        /// </summary>
        public InputAction @DeleteMarcher => m_Wrapper.m_Gameplay_DeleteMarcher;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/SelectAll".
        /// </summary>
        public InputAction @SelectAll => m_Wrapper.m_Gameplay_SelectAll;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/GizmoPosition".
        /// </summary>
        public InputAction @GizmoPosition => m_Wrapper.m_Gameplay_GizmoPosition;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/GizmoRotate".
        /// </summary>
        public InputAction @GizmoRotate => m_Wrapper.m_Gameplay_GizmoRotate;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/GizmoScale".
        /// </summary>
        public InputAction @GizmoScale => m_Wrapper.m_Gameplay_GizmoScale;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/SnapToGrid".
        /// </summary>
        public InputAction @SnapToGrid => m_Wrapper.m_Gameplay_SnapToGrid;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/RespaceToBox".
        /// </summary>
        public InputAction @RespaceToBox => m_Wrapper.m_Gameplay_RespaceToBox;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/FocusCamera".
        /// </summary>
        public InputAction @FocusCamera => m_Wrapper.m_Gameplay_FocusCamera;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/CameraZoomScroll".
        /// </summary>
        public InputAction @CameraZoomScroll => m_Wrapper.m_Gameplay_CameraZoomScroll;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/CameraRotate".
        /// </summary>
        public InputAction @CameraRotate => m_Wrapper.m_Gameplay_CameraRotate;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/CameraPivot".
        /// </summary>
        public InputAction @CameraPivot => m_Wrapper.m_Gameplay_CameraPivot;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/CameraPan".
        /// </summary>
        public InputAction @CameraPan => m_Wrapper.m_Gameplay_CameraPan;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/TouchContact0".
        /// </summary>
        public InputAction @TouchContact0 => m_Wrapper.m_Gameplay_TouchContact0;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/TouchContact1".
        /// </summary>
        public InputAction @TouchContact1 => m_Wrapper.m_Gameplay_TouchContact1;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/TouchDelta0".
        /// </summary>
        public InputAction @TouchDelta0 => m_Wrapper.m_Gameplay_TouchDelta0;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/TouchDelta1".
        /// </summary>
        public InputAction @TouchDelta1 => m_Wrapper.m_Gameplay_TouchDelta1;
        /// <summary>
        /// Provides access to the underlying input action "Gameplay/TouchCount".
        /// </summary>
        public InputAction @TouchCount => m_Wrapper.m_Gameplay_TouchCount;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GameplayActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @ConfirmDot.started += instance.OnConfirmDot;
            @ConfirmDot.performed += instance.OnConfirmDot;
            @ConfirmDot.canceled += instance.OnConfirmDot;
            @DeleteDot.started += instance.OnDeleteDot;
            @DeleteDot.performed += instance.OnDeleteDot;
            @DeleteDot.canceled += instance.OnDeleteDot;
            @DeleteMarcher.started += instance.OnDeleteMarcher;
            @DeleteMarcher.performed += instance.OnDeleteMarcher;
            @DeleteMarcher.canceled += instance.OnDeleteMarcher;
            @SelectAll.started += instance.OnSelectAll;
            @SelectAll.performed += instance.OnSelectAll;
            @SelectAll.canceled += instance.OnSelectAll;
            @GizmoPosition.started += instance.OnGizmoPosition;
            @GizmoPosition.performed += instance.OnGizmoPosition;
            @GizmoPosition.canceled += instance.OnGizmoPosition;
            @GizmoRotate.started += instance.OnGizmoRotate;
            @GizmoRotate.performed += instance.OnGizmoRotate;
            @GizmoRotate.canceled += instance.OnGizmoRotate;
            @GizmoScale.started += instance.OnGizmoScale;
            @GizmoScale.performed += instance.OnGizmoScale;
            @GizmoScale.canceled += instance.OnGizmoScale;
            @SnapToGrid.started += instance.OnSnapToGrid;
            @SnapToGrid.performed += instance.OnSnapToGrid;
            @SnapToGrid.canceled += instance.OnSnapToGrid;
            @RespaceToBox.started += instance.OnRespaceToBox;
            @RespaceToBox.performed += instance.OnRespaceToBox;
            @RespaceToBox.canceled += instance.OnRespaceToBox;
            @FocusCamera.started += instance.OnFocusCamera;
            @FocusCamera.performed += instance.OnFocusCamera;
            @FocusCamera.canceled += instance.OnFocusCamera;
            @CameraZoomScroll.started += instance.OnCameraZoomScroll;
            @CameraZoomScroll.performed += instance.OnCameraZoomScroll;
            @CameraZoomScroll.canceled += instance.OnCameraZoomScroll;
            @CameraRotate.started += instance.OnCameraRotate;
            @CameraRotate.performed += instance.OnCameraRotate;
            @CameraRotate.canceled += instance.OnCameraRotate;
            @CameraPivot.started += instance.OnCameraPivot;
            @CameraPivot.performed += instance.OnCameraPivot;
            @CameraPivot.canceled += instance.OnCameraPivot;
            @CameraPan.started += instance.OnCameraPan;
            @CameraPan.performed += instance.OnCameraPan;
            @CameraPan.canceled += instance.OnCameraPan;
            @TouchContact0.started += instance.OnTouchContact0;
            @TouchContact0.performed += instance.OnTouchContact0;
            @TouchContact0.canceled += instance.OnTouchContact0;
            @TouchContact1.started += instance.OnTouchContact1;
            @TouchContact1.performed += instance.OnTouchContact1;
            @TouchContact1.canceled += instance.OnTouchContact1;
            @TouchDelta0.started += instance.OnTouchDelta0;
            @TouchDelta0.performed += instance.OnTouchDelta0;
            @TouchDelta0.canceled += instance.OnTouchDelta0;
            @TouchDelta1.started += instance.OnTouchDelta1;
            @TouchDelta1.performed += instance.OnTouchDelta1;
            @TouchDelta1.canceled += instance.OnTouchDelta1;
            @TouchCount.started += instance.OnTouchCount;
            @TouchCount.performed += instance.OnTouchCount;
            @TouchCount.canceled += instance.OnTouchCount;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GameplayActions" />
        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @ConfirmDot.started -= instance.OnConfirmDot;
            @ConfirmDot.performed -= instance.OnConfirmDot;
            @ConfirmDot.canceled -= instance.OnConfirmDot;
            @DeleteDot.started -= instance.OnDeleteDot;
            @DeleteDot.performed -= instance.OnDeleteDot;
            @DeleteDot.canceled -= instance.OnDeleteDot;
            @DeleteMarcher.started -= instance.OnDeleteMarcher;
            @DeleteMarcher.performed -= instance.OnDeleteMarcher;
            @DeleteMarcher.canceled -= instance.OnDeleteMarcher;
            @SelectAll.started -= instance.OnSelectAll;
            @SelectAll.performed -= instance.OnSelectAll;
            @SelectAll.canceled -= instance.OnSelectAll;
            @GizmoPosition.started -= instance.OnGizmoPosition;
            @GizmoPosition.performed -= instance.OnGizmoPosition;
            @GizmoPosition.canceled -= instance.OnGizmoPosition;
            @GizmoRotate.started -= instance.OnGizmoRotate;
            @GizmoRotate.performed -= instance.OnGizmoRotate;
            @GizmoRotate.canceled -= instance.OnGizmoRotate;
            @GizmoScale.started -= instance.OnGizmoScale;
            @GizmoScale.performed -= instance.OnGizmoScale;
            @GizmoScale.canceled -= instance.OnGizmoScale;
            @SnapToGrid.started -= instance.OnSnapToGrid;
            @SnapToGrid.performed -= instance.OnSnapToGrid;
            @SnapToGrid.canceled -= instance.OnSnapToGrid;
            @RespaceToBox.started -= instance.OnRespaceToBox;
            @RespaceToBox.performed -= instance.OnRespaceToBox;
            @RespaceToBox.canceled -= instance.OnRespaceToBox;
            @FocusCamera.started -= instance.OnFocusCamera;
            @FocusCamera.performed -= instance.OnFocusCamera;
            @FocusCamera.canceled -= instance.OnFocusCamera;
            @CameraZoomScroll.started -= instance.OnCameraZoomScroll;
            @CameraZoomScroll.performed -= instance.OnCameraZoomScroll;
            @CameraZoomScroll.canceled -= instance.OnCameraZoomScroll;
            @CameraRotate.started -= instance.OnCameraRotate;
            @CameraRotate.performed -= instance.OnCameraRotate;
            @CameraRotate.canceled -= instance.OnCameraRotate;
            @CameraPivot.started -= instance.OnCameraPivot;
            @CameraPivot.performed -= instance.OnCameraPivot;
            @CameraPivot.canceled -= instance.OnCameraPivot;
            @CameraPan.started -= instance.OnCameraPan;
            @CameraPan.performed -= instance.OnCameraPan;
            @CameraPan.canceled -= instance.OnCameraPan;
            @TouchContact0.started -= instance.OnTouchContact0;
            @TouchContact0.performed -= instance.OnTouchContact0;
            @TouchContact0.canceled -= instance.OnTouchContact0;
            @TouchContact1.started -= instance.OnTouchContact1;
            @TouchContact1.performed -= instance.OnTouchContact1;
            @TouchContact1.canceled -= instance.OnTouchContact1;
            @TouchDelta0.started -= instance.OnTouchDelta0;
            @TouchDelta0.performed -= instance.OnTouchDelta0;
            @TouchDelta0.canceled -= instance.OnTouchDelta0;
            @TouchDelta1.started -= instance.OnTouchDelta1;
            @TouchDelta1.performed -= instance.OnTouchDelta1;
            @TouchDelta1.canceled -= instance.OnTouchDelta1;
            @TouchCount.started -= instance.OnTouchCount;
            @TouchCount.performed -= instance.OnTouchCount;
            @TouchCount.canceled -= instance.OnTouchCount;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />.
        /// </summary>
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
        /// <seealso cref="GameplayActions.UnregisterCallbacks(IGameplayActions)" />
        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GameplayActions" /> instance referencing this action map.
    /// </summary>
    public GameplayActions @Gameplay => new GameplayActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Gameplay" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GameplayActions.AddCallbacks(IGameplayActions)" />
    /// <seealso cref="GameplayActions.RemoveCallbacks(IGameplayActions)" />
    public interface IGameplayActions
    {
        /// <summary>
        /// Method invoked when associated input action "ConfirmDot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnConfirmDot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DeleteDot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDeleteDot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DeleteMarcher" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDeleteMarcher(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectAll" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectAll(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GizmoPosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGizmoPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GizmoRotate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGizmoRotate(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GizmoScale" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGizmoScale(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SnapToGrid" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSnapToGrid(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RespaceToBox" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRespaceToBox(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FocusCamera" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFocusCamera(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CameraZoomScroll" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraZoomScroll(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CameraRotate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraRotate(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CameraPivot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraPivot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CameraPan" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraPan(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchContact0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchContact0(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchContact1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchContact1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchDelta0" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchDelta0(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchDelta1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchDelta1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchCount" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchCount(InputAction.CallbackContext context);
    }
}
